<div class="login-box">
  <div class="login-logo">
    <b>App</b>Skeleton
  </div>
  <div class="card">
    <div class="card-body login-card-body">
      <p class="login-box-msg">Forgot your password?</p>

      <form method="post" action="<?= $this->url->get('backend/password/send') ?>">
        <div class="input-group mb-3">
          <label for="email" class="sr-only">Email</label>
          <input type="email" class="form-control" id="email" name="email" placeholder="Email" required>
          <div class="input-group-append">
            <div class="input-group-text"><span class="fas fa-envelope" aria-hidden="true"></span></div>
          </div>
        </div>
        <div class="row">
          <div class="col-12">
            <button type="submit" class="btn btn-primary btn-block">Send reset link</button>
          </div>
        </div>
      </form>

      <p class="mt-3 mb-0">
        <a href="<?= $this->url->get('backend/session') ?>">Back to sign in</a>
      </p>
    </div>
  </div>
</div>
